name: Secrets
on: push
jobs:
  print-secrets:
    runs-on: ubuntu-latest
    env:
      WELCOME: ${{ secrets.WELCOME }}
    steps:
      - run: echo "${WELCOME}"
      - run: echo "${WELCOME:0:1} ${WELCOME#?}"
